; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; src_dir = examples/epd_display_test
; src_dir = examples/sd_test
; src_dir = examples/wifi_scan
src_dir = examples/factory_test


boards_dir = boards

[env:T5_E_PAPER_BASIC]
platform = espressif32@6.13.0
board = T5-ePaper-S3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	
	-DCORE_DEBUG_LEVEL=0
	
	
	-DDISABLE_ALL_LIBRARY_WARNINGS
	
	-Wl,--gc-sections
lib_deps = 
	Wire
	SPI
	m5stack/M5GFX@^0.2.24
	lewisxhe/SensorLib@^0.4.1
